# Dockerfile.dev
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Map your code volume
VOLUME ["/app/node_modules", "/app"]

# Expose the port the app runs on
EXPOSE 3000

# Command to run the app
CMD ["npm", "start"]
