version: '3.8'

services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./Backend/src:/usr/src/app/src
    command: ["nodemon", "--exec", "ts-node", "./src/index.ts"]
