version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev  # Or Dockerfile.prod depending on the environment
    ports:
      - "4000:4000"
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development  # Or 'production' based on your setup
    networks:
      - internal

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev  # Or Dockerfile.prod depending on the environment
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development  # Or 'production' based on your setup
    networks:
      - internal
    depends_on:
      - backend

networks:
  internal:
    name: internal
    driver: bridge
