version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    volumes: []
    environment:
      NODE_ENV: production
    command: ["node", "dist/index.js"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    volumes: []
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
