# Use the official Node.js 16 image as the base
FROM node:16

# Set the working directory in the Docker container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or npm-shrinkwrap.json) to Docker environment
COPY package*.json ./

# Install all dependencies including devDependencies for development
RUN npm install

# Copy the rest of your application's source code from the host to the Docker container
COPY . .

# Expose the port the app runs on
EXPOSE 4000

# Set environment variable to development (useful for conditional configurations in app)
ENV NODE_ENV=development

# Use npx to run nodemon
CMD ["npx", "nodemon", "--exec", "ts-node", "src/index.ts"]