# Use the official Node.js 16 image as a parent image
FROM node:16

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install global dependencies
RUN npm install -g nodemon

# Copy package.json and package-lock.json (or npm-shrinkwrap.json)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Bind the port that the app runs on
EXPOSE 4000

# Mount the source code into the container, the code is run directly from here
# The actual source directory will be mounted at runtime
CMD ["nodemon", "--exec", "ts-node", "./src/index.ts"]
